name = "ceylon-travels"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_APP_URL = "https://ceylon-travel-cloudflare.pages.dev"
NEXT_PUBLIC_API_URL = "https://ceylon-travel-cloudflare.pages.dev"
BETTER_AUTH_URL = "https://ceylon-travel-cloudflare.pages.dev"
